version: '3' # vs mais atual
networks:
  nlw-app-network:
    driver: bridge
services:             

  app:
    build: nodejs
    container_name: nlw-05-nodejs
    restart: always
    tty: true
    networks:
      - nlw-app-network
    ports:
      - "3333:3333"
    volumes:       
      - ./nodejs:/src/app
    working_dir: /src/app
    environment:
      # ESCOLHA O SEU DRIVE ENTRE sqlite, mysql E postgres
      - CONNECTION_DRIVE=sqlite
      # CONFIGURAÇÕES MIGRATIONS
      - TYPE_ORM_LOGGING=true
      - TYPE_ORM_ENTITIES=./src/entities/*.ts
      - TYPE_ORM_MIGRATIONS=./src/database/migrations/**.ts
      - TYPE_ORM_MIGRATIONS_DIR=./src/database/migrations
      - TYPE_ORM_ENTITIES_DIR=./src/entities/**.ts